### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by ParamToor** [150-lab2/Project_SafeWalk#10]
# Todo 

- [ ] create a contacts page (UX)
- [ ] design the contacts page (front-end)
- [ ] implement functions such as; add, remove, and modify contacts (back-end)
- [ ] test contacts page (QA)
