### ISSUE TITLE
Panic Button

### ISSUE THREAD

**Issue by ParamToor** [150-lab2/Project_SafeWalk#11]
# Todo

- [ ] design button (UX)
- [ ] display button (front-end)
- [ ] create button (back-end)
- [ ] test button (QA)
