### ISSUE TITLE
User Registration and Login page

### ISSUE THREAD

**Issue by ParamToor** [150-lab2/Project_SafeWalk#8]
#Todo
 - [ ] create a wireframe for main screens (UX)
 - [ ] design login and user registration pages (front-end)
 - [ ] user registration and authorization (back-end)
 - [ ] test login functions (QA)
