### ISSUE TITLE
Location Tracking

### ISSUE THREAD

**Issue by ParamToor** [150-lab2/Project_SafeWalk#9]
# Todo

- [ ] develop main dashboard (front-end)
- [ ] review dashboard with front-end (UX)
- [ ] implement location tracking (back-end)
- [ ] test functionalities (QA)
